<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'article' => '/Article.php',
                'articlewithmultipleoptions' => '/ArticleWithMultipleOptions.php',
                'articlewithoneoption' => '/ArticleWithOneOption.php',
                'articlewithoutoptions' => '/ArticleWithoutOptions.php',
                'currency' => '/Currency.php',
                'money' => '/Money.php',
                'option' => '/Option.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
